### PR TITLE
add youtube videos to tutorials (resolves #65)

### LINKED ISSUE #65: add youtube videos to tutorials
https://www.youtube.com/playlist?list=PL5Edc1v41fyBlbysy_1750IiT2xk6sDqO  
should be added to tutorials page

### PR DESCRIPTION
**Pull request by N3llz**

### CODE REVIEW

**Comment by mcquin** [comment]
screen shot 2016-10-13 at 1 56 29 pm

I would expect "Pipeline example to find individual worms [PDF]" to appear in the same section as "Worm Toolbox." 

"More CellProfiler Getting Started Tutorials [YouTube]" and "For an introductory tutorial to construct pipelines, visit [YouTube]." seem redundant.

**Comment by N3llz** [comment]
@mcquin @AnneCarpenter Do you think I should call it something like "A set of introductory video tutorials developed by a CellProfiler user" ... this is referring to the youtube series that Neil Anthony made. Should we also link to his website page? http://www.cores.emory.edu/ici/resources/youtube_tutorials.html

**Comment by AnneCarpenter** [comment]
Yes, check his original thread to be sure but I recall he did prefer us to link to his page rather than straight to Youtube. And yes, that title is good, maybe delete "a set of".

**Comment by N3llz** [comment]
@mcquin please review... I reorganized the youtube links and also some content that seemed out of place

**Pull request merged**
